[tool.vulture]
exclude = ["migrations/env.py"]
ignore_decorators = ["@cross_origin", "@token_required*"]
ignore_names = []
make_whitelist = true
min_confidence = 80
paths = ["app","workers","manage.py"]
sort_by_size = true
verbose = true

[tool.pylint]
ignore-paths = ["^migrations/.*$"]
good-names = ["r","q","e","id","s3","f","get-pip"]


[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = true
ignore-module = false
ignore-nested-functions = true
ignore-nested-classes = false
ignore-setters = false
fail-under = 95
#ignore-regex = ["^get$", "^__.*", ".*BaseClass.*"]
# possible values: 0 (minimal output), 1 (-v), 2 (-vv)
verbose = 2
quiet = false
whitelist-regex = []
color = true
omit-covered-files = true
