# PostgresSQL

ADMIN:
  NAME: "InitialUser"
  PRIMARY_EMAIL: "admin@project.com"
  PRIMARY_PHONE: "9876543210"
  PIN: "12345"

APP_CONFIG_PATH: "config/app_config.yml"

APP_ENV: "DEV"
POSTGRES_USER: "postgres"
POSTGRES_PW: "1234"
POSTGRES_URL: "127.0.0.1:5432"
POSTGRES_DB: "boiler_plate"

AWS:
  S3_BUCKET: ""
  S3_BUCKET_URL: ""

MAIL:
  MAIL_SERVER: "live.smtp.mailtrap.io"
  MAIL_PORT: 587
  MAIL_USERNAME: "api"
  MAIL_PASSWORD: "189250e6a4bdc77539df63cc6d5f14f9"
  MAIL_USE_TLS: True
  MAIL_USE_SSL: False
  MAIL_DEFAULT_SENDER: 'mailtrap@demomailtrap.com'
  MAIL_DEFAULT_SENDER_NAME: "mailtrap"

RATE_LIMIT: # Used by Flask-Limiter
  STRATEGY: "moving-window"
  KEY_PREFIX: "RATE_LIMITING"
  REDIS_DB: 1

REDIS: # Used to initialize redis objects
  HOST: "localhost"
  PORT: 6379
  DB: 0

SQLALCHEMY_DATABASE_URI: "postgresql://postgres:1234@127.0.0.1:5432/boiler_plate"
SQLALCHEMY_TRACK_MODIFICATIONS: False
SQLALCHEMY_ENGINE_OPTIONS: { "isolation_level": "AUTOCOMMIT" }
CELERY_BROKER_URL: "pyamqp://lims_root_rabbitmq:Ey6ftnhsdyRL6Lpg@localhost:5672/lims_rabbitmq"
LOG_FILE_PATH: "/home/bs/Desktop/flask/flask-boilerplate-prod/app.log"
JWT_SALT: "1234567890"
HASH_ID_SALT: "0987654321"
PASSWORD_SALT: "qwertyuiop"
SECRET_KEY: "12345678"
RQ_JOB_TIMEOUT: 100000

SQLALCHEMY_TEST_DATABASE_URI: "postgresql://postgres:1234@127.0.0.1:5432/flask_boiler_test"
TESTING: False

SWAGGER_FILE_NAME: "swagger"

UPLOAD_FOLDER : '/home/bs/Desktop/flask/flask-boilerplate-prod/media'
