# PostgresSQL

ADMIN:
  NAME: "InitialUser"
  PRIMARY_EMAIL: "admin@project.com"
  PRIMARY_PHONE: "9876543210"
  PIN: "12345"

APP_CONFIG_PATH: "config/app_config.yml"

APP_ENV: "DEV"
POSTGRES_USER: "root_user"
POSTGRES_PW: "XgKx7DQ2dUmYcL56"
POSTGRES_URL: "127.0.0.1:5432"
POSTGRES_DB: "boiler_plate"

MAIL:
  MAIL_SERVER: "smtp.mailgun.org"
  MAIL_PORT: 465
  MAIL_USERNAME: "something@notifications.active.space"
  MAIL_PASSWORD: "966f"
  MAIL_USE_TLS: False
  MAIL_USE_SSL: True
  MAIL_DEFAULT_SENDER: "info@active.space"
  MAIL_DEFAULT_SENDER_NAME: "BoilerPlate"

RATE_LIMIT: # Used by Flask-Limiter
  STRATEGY: "moving-window"
  KEY_PREFIX: "RATE_LIMITING"
  REDIS_DB: 1

REDIS: # Used to initialize redis objects
  HOST: "localhost"
  PORT: 6379
  DB: 0

SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:new_password@127.0.0.1:5432/boiler_plate"
SQLALCHEMY_TRACK_MODIFICATIONS: False
SQLALCHEMY_ENGINE_OPTIONS: { "isolation_level": "AUTOCOMMIT" }
UPLOAD_FOLDER: "/opt/edugem/logs/flask_boiler_plate/media/"
CELERY_BROKER_URL: "pyamqp://lims_root_rabbitmq:Ey6ftnhsdyRL6Lpg@localhost:5672/lims_rabbitmq"
LOG_FILE_PATH: "/opt/edugem/logs/flask_boiler_plate/app.log"
JWT_SALT: "1234567890"
HASH_ID_SALT: "0987654321"
PASSWORD_SALT: "qwertyuiop"
SECRET_KEY: "123412"
RQ_JOB_TIMEOUT: 100000

SQLALCHEMY_TEST_DATABASE_URI: "postgresql+psycopg2://postgres:new_password@127.0.0.1:5432/flask_boiler_test"
TESTING: False

SWAGGER_FILE_NAME: "swagger"
